version: "3.9"

services:
  application:
    build:
      context: .devcontainer
      args:
        - USER=${REMOTE_USER}
        - WORKSPACES=${WORKSPACES}
        - HOME=${REMOTE_HOME}
    container_name: ${CONTAINER_NAME}
    working_dir: ${WORKSPACES}
    user: ${REMOTE_USER}
    tty: true
    volumes:
      - type: bind
        source: .
        target: ${PROJECT_ROOT}
      - type: volume
        source: dot_slack
        target: ${REMOTE_HOME}/.slack
      - type: volume
        source: bash_history
        target: /commandhistory
      - type: volume
        source: vscode_extensions
        target: ${REMOTE_HOME}/.vscode-server/extensions

volumes:
  bash_history:
    name: ${BASH_HISTORY_VOLUME_NAME}
  vscode_extensions:
    name: ${VSCODE_EXTENSIONS_VOLUME_NAME}
  dot_slack:
    name: ${DOT_SLACK_VOLUME_NAME}
